### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by wyz155** [UltraThiccCat/CSGO-GlowHack-Demo#1]
Hello, how do I compile this? I didn’t see the .sin project, sorry I’m a newbie

**Comment by UltraThiccCat** [comment]
My bad sorry, I also apologise for my late response.

If you have any further questions you can contact me on Discord.

UltraThiccCat#1337

You can expect a much faster response from me there!

I will attach a full solution below!


[GlowHack.zip](https://github.com/UltraThiccCat/CSGO-GlowHack-Demo/files/4745520/GlowHack.zip)
